//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_api_2_portfolio_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public System.Guid RoleID { get; set; }
        public string RoleName { get; set; }
    }
}
